// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student_Management_System__Sprint_5_Tawjeh_.Data;

#nullable disable

namespace Student_Management_System__Sprint_5_Tawjeh_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002214350_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Student_Management_System__Sprint_5_Tawjeh_.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 3,
                            Description = "Fundamental concepts of programming and computational thinking.",
                            InstructorId = 1,
                            Title = "Introduction to Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 4,
                            Description = "Relational database design, SQL, and modern ORM frameworks.",
                            InstructorId = 2,
                            Title = "Database Systems"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 4,
                            Description = "Core data structures: lists, trees, graphs, and algorithm analysis.",
                            InstructorId = 1,
                            Title = "Data Structures and Algorithms"
                        },
                        new
                        {
                            Id = 4,
                            Credits = 3,
                            Description = "Frontend and backend web development with modern frameworks.",
                            InstructorId = 3,
                            Title = "Web Development"
                        });
                });

            modelBuilder.Entity("Student_Management_System__Sprint_5_Tawjeh_.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 88,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 92,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 76,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 4,
                            EnrollmentDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 85,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 95,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 78,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 4,
                            EnrollmentDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 90,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4
                        });
                });

            modelBuilder.Entity("Student_Management_System__Sprint_5_Tawjeh_.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Dr. Sarah Johnson"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Prof. Ahmed Hassan"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Dr. Emily Chen"
                        });
                });

            modelBuilder.Entity("Student_Management_System__Sprint_5_Tawjeh_.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2000, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.mohamed@university.edu",
                            EnrollmentDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ali Mohamed",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2001, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.ahmed@university.edu",
                            EnrollmentDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sara Ahmed",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1999, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.khaled@university.edu",
                            EnrollmentDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Omar Khaled",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2002, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nour.hassan@university.edu",
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nour Hassan",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Student_Management_System__Sprint_5_Tawjeh_.Entities.Course", b =>
                {
                    b.HasOne("Student_Management_System__Sprint_5_Tawjeh_.Entities.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Student_Management_System__Sprint_5_Tawjeh_.Entities.Enrollment", b =>
                {
                    b.HasOne("Student_Management_System__Sprint_5_Tawjeh_.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Student_Management_System__Sprint_5_Tawjeh_.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Student_Management_System__Sprint_5_Tawjeh_.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Student_Management_System__Sprint_5_Tawjeh_.Entities.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Student_Management_System__Sprint_5_Tawjeh_.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
